version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=booking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/db

  booking_app-END:
    container_name: booking_app
    image: booking_app
    build:
      context: .
      dockerfile: Dockerfile
    #    environment:
    #      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/booking
    #      SPRING_DATASOURCE_USERNAME: postgres
    #      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - "8080:8080"

    tty: true
    stdin_open: true

volumes:
  postgres_data: